[versions]
# Plugins
kotlin = "1.7.22"
android = "7.3.1"
versionUpdater = "0.44.0"
ktlint = "11.0.0"
dokka = "1.7.21"
mavenRelease = "0.22.0"

# AndroidX libraries
compatLibrary = "1.4.2"
annotationsLibrary = "1.4.0"
materialLibrary = "1.6.1"
startupLibrary = "1.1.1"

# Third party Libraries
googleAdsId = "18.0.1"
huaweiAdsId = "3.4.26.303"
retrofit = "2.6.4"
okhttp = "3.12.13"
moshi = "1.13.0"
timber = "5.0.1"
viewBindingProperty = "1.5.6"

# Test Libraries
junit = "4.13.2"
androidxTestCore = "1.4.0"
mockitoKotlin = "2.2.0"
mockitoCore = "3.4.6"
robolectric = "4.8.2"

[plugins]
android-library = { id = "com.android.library", version.ref = "android" }
android-app = { id = "com.android.application", version.ref = "android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
mavenRelease = { id = "com.vanniktech.maven.publish", version.ref = "mavenRelease" }
versionUpdater = { id = "com.github.ben-manes.versions", version.ref = "versionUpdater" }

[libraries]
annotations = { module = "androidx.annotation:annotation", version.ref = "annotationsLibrary" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "compatLibrary" }
material = { module = "com.google.android.material:material", version.ref = "materialLibrary" }
startup = { module = "androidx.startup:startup-runtime", version.ref = "startupLibrary" }
googleAdsId = { module = "com.google.android.gms:play-services-ads-identifier", version.ref = "googleAdsId" }
huaweiAdsId = { module = "com.huawei.hms:hms-ads-identifier", version.ref = "huaweiAdsId" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitConverter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttpLogging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshiCodegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
viewBindingProperty = { module = "com.github.kirich1409:viewbindingpropertydelegate", version.ref = "viewBindingProperty" }

kotlinJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
mockitoKotlin = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version.ref = "mockitoKotlin" }
mockitoCore = { module = "org.mockito:mockito-core", version.ref = "mockitoCore" }
junit = { module = "junit:junit", version.ref = "junit" }
androidxTestCore = { module = "androidx.test:core-ktx", version.ref = "androidxTestCore" }
okhttpMockServer = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
